spring.application.name=SaaS ERP Core
server.port=8080

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml

spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.url=jdbc:postgresql://localhost:5432/saaserpcore
spring.datasource.driver-class-name=org.postgresql.Driver